// @ts-ignore `.open-next/worker.js` is generated by `npm run build:cloudflare`.
import handler from "./.open-next/worker.js";

type CloudflareEnv = {
  CRON_SECRET?: string;
};

type ScheduledController = {
  cron: string;
};

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

const cronRoutes: Record<string, string[]> = {
  "*/10 * * * *": ["/api/broadcasts/run"],
  "0 * * * *": ["/api/broadcast-followups/run"],
  "0 22 * * *": ["/api/ai/next-actions/run?limit=100"],
  "55 14 * * *": ["/api/cron/recruiting-monthly-snapshot"]
};

async function callNextRoute(path: string, env: CloudflareEnv, ctx: WorkerContext) {
  const headers = new Headers();
  if (env.CRON_SECRET) {
    headers.set("x-cron-secret", env.CRON_SECRET);
  }

  const request = new Request(`https://worker.local${path}`, {
    method: "GET",
    headers
  });

  const response = await handler.fetch(request, env, ctx);
  if (!response.ok) {
    throw new Error(`Cron route failed: ${path} (${response.status})`);
  }
}

export default {
  fetch: handler.fetch,
  async scheduled(controller: ScheduledController, env: CloudflareEnv, ctx: WorkerContext) {
    for (const path of cronRoutes[controller.cron] ?? []) {
      ctx.waitUntil(callNextRoute(path, env, ctx));
    }
  }
};
