insert into public.students (
  id,
  line_user_id,
  display_name,
  real_name,
  kana,
  university,
  grade,
  graduation_year,
  practical_period,
  phone,
  email,
  desired_job_type,
  desired_area,
  motivation_level,
  first_contact_method,
  first_contact_date,
  last_inbound_at,
  last_outbound_at,
  ai_next_action,
  manual_next_action,
  status
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    'UstudentDemo001',
    'Hana Sato',
    'Hana Sato',
    'SATO HANA',
    'Tokyo Pharmacy University',
    '5',
    2027,
    'P2_3',
    '090-1111-2222',
    'hana.sato@example.jp',
    'Community pharmacy',
    'Tokyo / Kanagawa',
    5,
    'Career fair',
    '2026-04-12',
    now() - interval '1 day',
    now() - interval '4 days',
    'Send three store visit date options this week',
    'Check visit date candidates by LINE on 2026-05-20',
    'active'
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    'UstudentDemo002',
    'Ryo Suzuki',
    'Ryo Suzuki',
    'SUZUKI RYO',
    'Meiji Pharmaceutical University',
    '4',
    2028,
    'undecided',
    '090-3333-4444',
    'ryo.suzuki@example.jp',
    'Hospital pharmacist also considered',
    'Saitama',
    3,
    'LINE follow',
    '2026-05-01',
    now() - interval '8 days',
    now() - interval '3 days',
    'Send a light reminder because there is no reply',
    null,
    'active'
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    'UstudentDemo003',
    'Misaki Tanaka',
    'Misaki Tanaka',
    'TANAKA MISAKI',
    'Kitasato University',
    '6',
    2026,
    'P3_4',
    '090-5555-6666',
    'misaki.tanaka@example.jp',
    'Drugstore pharmacist',
    'Chiba',
    4,
    'Campus seminar',
    '2026-03-20',
    now() - interval '2 days',
    now() - interval '2 days',
    'Ask about concerns before interview',
    'Schedule next Zoom interview',
    'active'
  )
on conflict (id) do update
set
  line_user_id = excluded.line_user_id,
  display_name = excluded.display_name,
  real_name = excluded.real_name,
  kana = excluded.kana,
  university = excluded.university,
  grade = excluded.grade,
  graduation_year = excluded.graduation_year,
  practical_period = excluded.practical_period,
  phone = excluded.phone,
  email = excluded.email,
  desired_job_type = excluded.desired_job_type,
  desired_area = excluded.desired_area,
  motivation_level = excluded.motivation_level,
  first_contact_method = excluded.first_contact_method,
  first_contact_date = excluded.first_contact_date,
  last_inbound_at = excluded.last_inbound_at,
  last_outbound_at = excluded.last_outbound_at,
  ai_next_action = excluded.ai_next_action,
  manual_next_action = excluded.manual_next_action,
  status = excluded.status;