insert into public.students (
  id,
  line_user_id,
  display_name,
  real_name,
  kana,
  university,
  grade,
  graduation_year,
  practical_period,
  phone,
  email,
  desired_job_type,
  desired_area,
  motivation_level,
  first_contact_method,
  first_contact_date,
  last_inbound_at,
  last_outbound_at,
  ai_next_action,
  manual_next_action,
  status
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    'UstudentDemo001',
    '菴占陸 闃ｱ',
    '菴占陸 闃ｱ',
    '繧ｵ繝医え 繝上リ',
    '譚ｱ莠ｬ阮ｬ遘大､ｧ蟄ｦ',
    '5蟷ｴ',
    2027,
    'P2_3',
    '090-1111-2222',
    'hana.sato@example.jp',
    '阮ｬ螻阮ｬ蜑､蟶ｫ',
    '譚ｱ莠ｬ繝ｻ逾槫･亥ｷ・,
    5,
    '蜷亥酔隱ｬ譏惹ｼ・,
    '2026-04-12',
    now() - interval '1 day',
    now() - interval '4 days',
    '莉企ｱ荳ｭ縺ｫ蠎苓・隕句ｭｦ縺ｮ譌･遞句呵｣懊ｒ3縺､騾√ｋ',
    '5/20 縺ｫLINE縺ｧ隕句ｭｦ蛟呵｣懈律繧堤｢ｺ隱・,
    'active'
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    'UstudentDemo002',
    '驤ｴ譛ｨ 莠ｮ',
    '驤ｴ譛ｨ 莠ｮ',
    '繧ｹ繧ｺ繧ｭ 繝ｪ繝ｧ繧ｦ',
    '譏取ｲｻ阮ｬ遘大､ｧ蟄ｦ',
    '4蟷ｴ',
    2028,
    'undecided',
    '090-3333-4444',
    'ryo.suzuki@example.jp',
    '逞・劼阮ｬ蜑､蟶ｫ繧よ､懆ｨ・,
    '蝓ｼ邇・,
    3,
    'LINE蜿九□縺｡霑ｽ蜉',
    '2026-05-01',
    now() - interval '8 days',
    now() - interval '3 days',
    '霑比ｿ｡縺後↑縺・◆繧∬ｻｽ縺・Μ繝槭う繝ｳ繝峨ｒ騾√ｋ',
    null,
    'active'
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    'UstudentDemo003',
    '逕ｰ荳ｭ 鄒主調',
    '逕ｰ荳ｭ 鄒主調',
    '繧ｿ繝翫き 繝溘し繧ｭ',
    '蛹鈴㈹螟ｧ蟄ｦ',
    '6蟷ｴ',
    2026,
    'P3_4',
    '090-5555-6666',
    'misaki.tanaka@example.jp',
    '繝峨Λ繝・げ繧ｹ繝医い',
    '蜊・痩',
    4,
    '蟄ｦ蜀・そ繝溘リ繝ｼ',
    '2026-03-20',
    now() - interval '2 days',
    now() - interval '2 days',
    '髱｢謗･蜑阪↓荳榊ｮ臥せ繧偵ヲ繧｢繝ｪ繝ｳ繧ｰ縺吶ｋ',
    '谺｡蝗杙oom髱｢隲・ｒ險ｭ螳・,
    'active'
  )
on conflict (id) do update
set
  line_user_id = excluded.line_user_id,
  display_name = excluded.display_name,
  real_name = excluded.real_name,
  kana = excluded.kana,
  university = excluded.university,
  grade = excluded.grade,
  graduation_year = excluded.graduation_year,
  practical_period = excluded.practical_period,
  phone = excluded.phone,
  email = excluded.email,
  desired_job_type = excluded.desired_job_type,
  desired_area = excluded.desired_area,
  motivation_level = excluded.motivation_level,
  first_contact_method = excluded.first_contact_method,
  first_contact_date = excluded.first_contact_date,
  last_inbound_at = excluded.last_inbound_at,
  last_outbound_at = excluded.last_outbound_at,
  ai_next_action = excluded.ai_next_action,
  manual_next_action = excluded.manual_next_action,
  status = excluded.status;